config/routes.rb
ParkcheckLpr::Application.routes.draw do
  resources :license_plates, only: [:index] do
    collection do
      post 'plate_scanned'
      delete 'delete_all_results'
    end
  end

end

app/models/lpr_result.rb
class LprResult < ActiveRecord::Base
  has_attached_file :image
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def image_url
    self.image.url
  end

  def save_image?
   !self.allowed_to_park
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/license_plates_controller.rb
class LicensePlatesController < ApplicationController
  skip_before_filter :verify_authenticity_token
  include LicensePlatesHelper

  def index
    @results = LprResult.where(control_car: params[:car_nr]).order(created_at: :desc)
  end

  def plate_scanned
    begin
      plate_info = get_plate_info
      lpr_result = save_lpr_result(plate_info)
      publish_lpr_result(lpr_result)
      render json: {result: true}.to_json
    rescue Exception => e

      render json: {result: false}.to_json
    end
  end


  def delete_all_results
    unless params[:car_nr].blank?
      LprResult.destroy_all(control_car: params[:car_nr].upcase)
    end
    redirect_to license_plates_path(car_nr: params[:car_nr].upcase)
  end

  private


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/license_plates_helper.rb
module LicensePlatesHelper
  def get_plate_info
    {
        plate: params[:plate],
        area: params[:area],
        control_car: params[:location],
        allowed_to_park: is_allowed_to_park(params[:plate])
    }
  end

  def is_allowed_to_park(license_plate)
    Random.rand > 0.5
  end


  def publish_lpr_result(lpr_result)
    request_body = {
        allowed_to_park: lpr_result.allowed_to_park,
        html: render_to_string(
            :partial => 'license_plates/lpr_result_row',
            :locals => {:result => lpr_result})
    }
    WebsocketRails[:control_car_results].trigger lpr_result.control_car, request_body
  end

  def save_lpr_result(plate_info)
    lpr_result = LprResult.new(plate_info)
    if lpr_result.save_image?
      lpr_result.image = params[:file]
    end
    lpr_result.save
    lpr_result
  end
end

app/views/layouts/_messages.html.erb
<%# flash types are: info, success, warning, danger %>

<% message_map = {}
   flash.each do |name, msg|
     key = name
     if name == :notice
       key = :info
     end
     if message_map.key?(key)
       message_map[key].push(msg)
     else
       if msg.is_a?(String)
         message_map[key] = [msg]
       elsif msg.is_a?(Array)
         message_map[key] = msg
       end
     end

   end %>

<% message_map.each_key do |key| %>
    <% if message_map[key].size == 0 %>
        <% next %>
    <% end %>
    <div class="form_validation_errors row">
      <div class="col-sm-8 alert alert-<%= key %> alert-dismissable">
            <button key="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <% message_map[key].each do |message| %>
            <div><%= message %></div>
        <% end %>
      </div>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ParkcheckLpr</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>
<body>
<div class="container-fluid">

  <div class="page_content">

    <div class="page_heading">
      <h2><%= yield(:title) %></h2>
    </div>

    <div id="messages-container">
      <%= render 'layouts/messages' %>
    </div>

    <div class="content_block">
      <%= yield %>
    </div>
    <!-- #content_block -->
  </div>
  <!-- /page_content -->

</div>
<!-- /container -->
</body>
</html>

app/views/license_plates/_lpr_result_row.erb
<tr>
  <td class="licence-plate">
    <input type="hidden" class="result-id" value="<%= result.id %>">
    <%= result.plate %>
  </td>
  <td class="controlled-at"><%= result.created_at.strftime('%d.%m.%y %H:%M:%S') %></td>
  <% if result.save_image? %>
      <td><%= image_tag result.image.url, width: 160, height: 90 %></td>
  <% end %>
</tr>

app/views/license_plates/_negative_results_table.erb
<h2>Parkimisõigus puudub (<span id="neg-result-count"><%= @results.where(allowed_to_park: false).size %></span>)</h2>
<table id="negative-result" class="table striped">
  <thead>
  <tr>
    <th>Numbimärk</th>
    <th>Kontrollitud</th>
    <th>Pilt</th>
  </tr>
  </thead>
  <tbody>
  <% @results.where(allowed_to_park: false).each do |res| %>
    <%= render 'license_plates/lpr_result_row', result: res %>
  <% end %>
  </tbody>
</table>

app/views/license_plates/_positive_results_table.erb
<h2>Kehtiva parkimisõigusega (<span id="pos-result-count"><%= @results.where(allowed_to_park: true).size %></span>)</h2>
<table id="positive-result" class="table striped">
  <thead>
  <tr>
    <th>Numbrimärk</th>
    <th>Kontrollitud</th>
  </tr>
  </thead>
  <tbody>
  <% @results.where(allowed_to_park: true).each do |res| %>
      <%= render 'license_plates/lpr_result_row', result: res %>
  <% end %>
  </tbody>
</table>

app/views/license_plates/_server_polling.erb
<script>
    <% unless params[:car_nr].blank? %>
    var dispatcher = new WebSocketRails('<%= websocket_url.split('//')[1]%>');

    // subscribe to the channel
    var channel = dispatcher.subscribe('control_car_results');

    // bind to a channel event
    channel.bind('<%= params[:car_nr].upcase %>', function (data) {
        if (data.allowed_to_park) {
            addNewRowToTable('#positive-result', data.html);
            $('#pos-result-count').html($('#positive-result tbody tr').size());
        } else {
            addNewRowToTable('#negative-result', data.html);
            $('#neg-result-count').html($('#negative-result tbody tr').size());
        }
    });
    <% end %>


    function addNewRowToTable(tableSelector, rowHtml) {
        var newRowPlace = $(tableSelector + ' tbody tr:first');
        if (newRowPlace.length > 0) {
            newRowPlace.before(rowHtml);
        } else {
            $(tableSelector + ' tbody').append(rowHtml)
        }
    }
</script>

app/views/license_plates/index.html.erb
<%= render 'server_polling' %>
<form class="form-inline" method="get">
  <div class="form-group">
    <label for="car_nr">Auto number</label>
    <input type="text" class="form-control" name="car_nr" id="car_nr" value="<%= params[:car_nr] %>">
  </div>
  <button type="submit" class="btn btn-default">Sisesta</button>
</form>
<% unless params[:car_nr].blank? %>
    <div class="row">
      <div class="col-sm-4"><%= render 'negative_results_table' %></div>
      <div class="col-sm-4"><%= render 'positive_results_table' %></div>
    </div>
    <p>
      <%= link_to 'Eemalda tulemused', delete_all_results_license_plates_path(car_nr: params[:car_nr]), method: :delete %>
    </p>
<% end %>